---
- name: Download awscliv2 installer.
  unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: /tmp
    remote_src: true
    creates: /tmp/aws
    mode: 0755

- name: Run the installer.
  command:
  args:
    cmd: "/tmp/aws/install"
    creates: /usr/local/bin/aws
  become: true
  register: aws_install

- name: "Show installer output."
  debug:
    var: aws_install
    verbosity: 2

- name: "Download kubectl"
  shell: curl -o kubectl curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.2/2023-10-17/bin/linux/amd64/kubectl
  args:
    chdir: $HOME

- name: "Apply execute permissions to kubectl"
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Copy the binary to bin"
  shell: mv kubectl /usr/local/bin
  args:
    chdir: $HOME

- name: "Copy the binary to bin"
  shell: kubectl
  args:
    chdir: $HOME

- name: "Get helm install script"
  shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
  args:
    chdir: $HOME

- name: "Execute permissions for get helm script"
  shell: chmod 700 get_helm.sh
  args:
   chdir: $HOME

- name: "Install Helm"
  shell: ./get_helm.sh
  args:
   chdir: $HOME