- name: Copy Helm Charts
  copy:
    src: "jokes-on-the-cloud"
    dest: $HOME

- name: Uninstall last deployment
  shell: "helm uninstall jokes-on-the-cloud"
  args:
    chdir: $HOME

- name: Apply deployment configuration
  shell: "helm install jokes-on-the-cloud jokes-on-the-cloud"
  args:
    chdir: $HOME

- name: Wait for ready state
  shell: "kubectl wait --for=condition=ready pod -l appName=jokes-on-the-cloud --timeout=60s"
  args:
    chdir: $HOME