- name: "Configure AWS CLI with Access Key"
  hosts: ec2
  user: ubuntu
  gather_facts: false
  become: true
  vars:
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
  tasks:
    - name: Set the AWS_ACCESS_KEY_ID
      shell: "aws configure set AWS_ACCESS_KEY_ID {{ AWS_ACCESS_KEY_ID }}"
    - name: Set the AWS_SECRET_ACCESS_KEY
      shell: "aws configure set AWS_SECRET_ACCESS_KEY {{ AWS_SECRET_ACCESS_KEY }}"
    - name: Set the AWS_DEFAULT_REGION 
      shell: "aws configure set AWS_DEFAULT_REGION {{ AWS_DEFAULT_REGION }}"