apiVersion: v1
kind: Service
metadata:
  name: {{ include "jokes-on-the-cloud.fullname" . }}
  labels:
    {{- include "jokes-on-the-cloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.appService.port }}
      targetPort: {{ .Values.appService.targetPort }}
      protocol: {{ .Values.appService.protocol }}
      name: https

  selector:
    {{- include "jokes-on-the-cloud.selectorLabels" . | nindent 4 }}
