---
- name: "Sever Configuration Play"
  hosts: ec2
  user: ubuntu
  become: true
  become_method: sudo
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"

  pre_tasks:

    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600

    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

    - name: "Install 'unzip'"
      apt:
        name: [ "unzip" ]
        state: latest
        update_cache: yes

  roles:
    - install-dependencies

- name: "Configure AWS CLI with Access Key"
  hosts: ec2
  user: ubuntu
  gather_facts: false
  become: true
  vars:
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
  tasks:
    - name: Print access key value
      shell: "echo 'Proof it exists - {{ AWS_ACCESS_KEY_ID }}'"
      register: key-test
    - name: Set the AWS_ACCESS_KEY_ID
      shell: "aws configure set AWS_ACCESS_KEY_ID {{ AWS_ACCESS_KEY_ID }}"
    - name: Set the AWS_SECRET_ACCESS_KEY
      shell: "aws configure set AWS_SECRET_ACCESS_KEY {{ AWS_SECRET_ACCESS_KEY }}"
    - name: Set the AWS_DEFAULT_REGION 
      shell: "aws configure set AWS_DEFAULT_REGION {{ AWS_DEFAULT_REGION }}"

    - debug: msg="{{ key-test.stdout }}"

- name: "Create kubeconfig"
  hosts: ec2
  user: ubuntu
  gather_facts: false
  become: true
  vars:
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  pre_tasks:
    - name: Create a kubeconfig file for the cluster
      shell: "aws eks update-kubeconfig --region {{ AWS_DEFAULT_REGION }} --name {{ ENVIRONMENT_NAME }}-kube-cluster"

