---
- name: "Save DNS Name"
  hosts: ec2
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  tasks:
    - name: Get the DNS name
      shell: "kubectl get --namespace default svc -w jokes-on-the-cloud"
      register: dns_name
      args:
        chdir: $HOME

    - name: Copy DNS output file
      copy:
        content: "{{ dns.stdout }}"
        dest: "~/dns.txt"
      delegate_to: localhost