---
- name: "Save DNS Name"
  hosts: ec2
  user: ubuntu
  gather_facts: false
  become: true
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: Get the DNS name
      shell: "kubectl get --namespace default svc jokes-on-the-cloud"
      register: dns_name
      args:
        chdir: $HOME

    - name: Copy DNS output file
      copy:
        content: "{{ dns_name.stdout }}"
        dest: "~/dns.txt"
      delegate_to: localhost